version: "3.7"

services:
  peripheral-manager-usb:
    build: .
    restart: on-failure
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
    network_mode: host
