version: "3.7"

services:
  peripheral-manager-usb:
    build: .
    restart: on-failure
    volumes:
      - /:/rootfs:ro
      - /dev:/dev:ro
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=nuvla.io
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    network_mode: host

