#!/usr/bin/env bash

#
# Generic client to delete a resource from Nuvla
#

set -o pipefail
set -e

resource_id=$1

if [[ -z ${resource_id} ]]
then
    echo "ERR: this script needs a resource ID as an input"
    exit 126
fi

nuvla_endpoint="https://"${NUVLA_ENDPOINT:-nuvla.io}
shared_directory=${SHARED:-/srv/nuvlabox/shared}

api_key=$(jq -r '."api-key"' ${shared_directory}/.activated)
secret_key=$(jq -r '."secret-key"' ${shared_directory}/.activated)

if [[ ! -z ${NUVLA_ENDPOINT_INSECURE} ]]
then
    extra_flags="-k"
else
    extra_flags=""
fi

cookies_file="${shared_directory}/cookies"

if [[ -f ${cookies_file} ]]
then
    # Cookies exist, but let's first see if they are still valid
    session_alive=$(curl -XGET --fail \
                        ${nuvla_endpoint}/api/session \
                        -H accept:application/json \
                        -b ${cookies_file} \
                        ${extra_flags} | jq '.count > 0')

    if [[ "${session_alive}" == "true" ]]
    then
        # Push resource to Nuvla
        (curl -XDELETE --fail \
            ${nuvla_endpoint}/api/${resource_id} \
            -H accept:application/json \
            -b ${cookies_file} -c ${cookies_file} \
            ${extra_flags} | jq -e '.status==200' &>/dev/null) || { echo "WARN: Cannot delete resource ${resource_id} in Nuvla"; exit 1; }
        exit 0
    fi
fi

# Then we have to login first
session_template='{
    "template": {
        "href": "session-template/api-key",
        "key": "'${api_key}'",
        "secret": "'${secret_key}'"
    }
}'

(curl -XPOST --fail \
    ${nuvla_endpoint}/api/session \
    -H content-type:application/json \
    -H accept:application/json \
    -c ${cookies_file} \
    ${extra_flags} \
    -d "${session_template}" | jq -e '.status==201' &>/dev/null) || { echo "ERR: can not login to ${nuvla_endpoint}"; exit 1; }


# Now we can push the resource
(curl -XDELETE --fail \
    ${nuvla_endpoint}/api/${resource_id} \
    -H accept:application/json \
    -b ${cookies_file} \
    ${extra_flags} | jq -e '.status==200' &>/dev/null) || { echo "WARN: Cannot delete resource ${resource_id} in Nuvla"; exit 1; }
