#!/usr/bin/env bash

#
# Generic client to delete a resource from Nuvla
#

set -o pipefail
set -e

resource_id=$1

if [[ -z ${resource_id} ]]
then
    echo "ERR: this script needs a resource ID as an input"
    exit 126
fi

nuvla_endpoint=${NUVLA_ENDPOINT:-nuvla.io}
shared_directory=${SHARED:-/srv/nuvlabox/shared}
cookies_file="${shared_directory}/cookies"

if [[ ! -z ${NUVLA_ENDPOINT_INSECURE} ]]
then
    extra_flags="-k"
else
    extra_flags=""
fi

nuvla-client-login "${nuvla_endpoint}" "${shared_directory}" "${cookies_file}" "${extra_flags}"

# Now we can delete the resource
status=$(curl -XDELETE \
          ${nuvla_endpoint}/api/${resource_id} \
          -H accept:application/json \
          -b ${cookies_file} \
          ${extra_flags} | jq -r '.status')


if [[ $status -eq 200 ]]
then
    exit 0
elif [[ $status -eq 404 ]]
then
    echo "INFO: ${resource_id} not found in Nuvla (404). Assuming it has already been deleted...moving on"
    exit 0
else
    echo "WARN: Cannot delete resource ${resource_id} in Nuvla"
    exit 1
fi
