#!/usr/bin/env bash

#
# Generic client to post a payload to Nuvla
#

set -o pipefail

resource=$1
payload=$2

if [[ ! -z ${payload} ]] || [[ "${payload}" != *} ]]
then
    (echo "${payload}" | jq -e . &>/dev/null) || { echo "ERR: the received payload is not a JSON"; exit 1; }
fi

if [[ -z ${resource} ]] || [[ -z ${payload} ]]
then
    echo "ERR: this script needs a payload and resource name as inputs"
    exit 126
fi

nuvla_endpoint=${NUVLA_ENDPOINT:-nuvla.io}

if [[ "${nuvla_endpoint}" != "https://"* ]] && [[ "${nuvla_endpoint}" != "http://"* ]]
then
  nuvla_endpoint="https://${nuvla_endpoint}"
fi

while [[ "${nuvla_endpoint: -1}" == "/" ]]
do
  nuvla_endpoint=$(echo "${nuvla_endpoint:: -1}")
done

shared_directory=${SHARED:-/srv/nuvlabox/shared}

api_key=$(jq -r '."api-key"' ${shared_directory}/.activated)
secret_key=$(jq -r '."secret-key"' ${shared_directory}/.activated)

if [[ ! -z ${NUVLA_ENDPOINT_INSECURE} ]]
then
    extra_flags="-k"
else
    extra_flags=""
fi

cookies_file="${shared_directory}/cookies"

if [[ -f ${cookies_file} ]]
then
    # Cookies exist, but let's first see if they are still valid
    session_alive=$(curl -XGET --fail \
                        ${nuvla_endpoint}/api/session \
                        -H accept:application/json \
                        -b ${cookies_file} \
                        ${extra_flags} | jq '.count > 0')

    if [[ "${session_alive}" == "true" ]]
    then
        # Push resource to Nuvla
        (curl -XPOST --fail \
            ${nuvla_endpoint}/api/${resource} \
            -H content-type:application/json \
            -H accept:application/json \
            -b ${cookies_file} -c ${cookies_file} \
            ${extra_flags} \
            -d "${payload}" | jq -re '."resource-id"') || { echo "WARN: Cannot create resource ${payload} in Nuvla"; exit 1; }
        exit 0
    fi
fi

# Then we have to login first
session_template='{
    "template": {
        "href": "session-template/api-key",
        "key": "'${api_key}'",
        "secret": "'${secret_key}'"
    }
}'

(curl -XPOST --fail \
    ${nuvla_endpoint}/api/session \
    -H content-type:application/json \
    -H accept:application/json \
    -c ${cookies_file} \
    ${extra_flags} \
    -d "${session_template}" | jq -e '.status==201' &>/dev/null) || { echo "ERR: can not login to ${nuvla_endpoint}"; exit 1; }


# Now we can push the resource
(curl -XPOST --fail \
    ${nuvla_endpoint}/api/${resource} \
    -H content-type:application/json \
    -H accept:application/json \
    -b ${cookies_file} \
    ${extra_flags} \
    -d "${payload}" | jq -re '."resource-id"') || { echo "WARN: Cannot create resource ${payload} in Nuvla"; exit 1; }
