#!/usr/bin/env bash

#
# Generic client to PUT a payload to Nuvla
#

set -o pipefail

resource_id=$1
payload=$2

if [[ ! -z ${payload} ]] || [[ "${payload}" != *} ]]
then
    (echo "${payload}" | jq -e . &>/dev/null) || { echo "ERR: the received payload is not a JSON"; exit 1; }
fi

if [[ -z ${resource_id} ]] || [[ -z ${payload} ]]
then
    echo "ERR: this script needs a payload and resource ID name as inputs"
    exit 126
fi

nuvla_endpoint=${NUVLA_ENDPOINT:-nuvla.io}

shared_directory=${SHARED:-/srv/nuvlabox/shared}
cookies_file="${shared_directory}/cookies"

if [[ "${NUVLA_ENDPOINT_INSECURE}" == "True" ]]
then
    extra_flags="-k"
else
    extra_flags=""
fi

nuvla-client-login "${nuvla_endpoint}" "${shared_directory}" "${cookies_file}" "${extra_flags}"

# Now we can edit the resource
(curl -XPUT --fail \
    ${nuvla_endpoint}/api/${resource_id} \
    -H content-type:application/json \
    -H accept:application/json \
    -b ${cookies_file} \
    ${extra_flags} \
    -d "${payload}" | jq -re .) || { echo "WARN: Cannot create resource ${payload} in Nuvla"; exit 1; }
